management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    web:
      server:
        requests:
          tags:
            status-codes: 4xx,5xx
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:18086/eureka/
      
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
