spring:
  profiles: local
eureka:
  client:
    fetch-registry: true # eureka 서버에 등록 여부
    service-url:
      defaultZone: http://localhost:18086/eureka/
logging:
  level:
    com:
      netflix: off
management:
  endpoints:
    web:
      exposure:
        include: '*' # 실서비스에선 반드시 *이 아닌 노출시킬 endpoint만 노출시키거나 보안 적용 필수적임
zuul:
  host:
    connect-timeout-millis: 3000
